# Generated by Django 4.1.7 on 2023-07-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "HOD"), (2, "Staff"), (3, "Student")],
                default=1,
                max_length=10,
            ),
        ),
    ]
