# Generated by Django 4.1.7 on 2023-07-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0004_staff_notification_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff_notification",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Staff_leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("status", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.staff",
                    ),
                ),
            ],
        ),
    ]
