# Generated by Django 4.1.7 on 2023-07-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0008_student_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_feedback",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student_feedback",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
